### ISSUE TITLE
/usr/lib64/libdl.so.2, but no libdl.so

### ISSUE THREAD

**Issue by zcsizmadia** [ied206/Joveler.DynLoader#1]
In CentOS 7  /usr/lib64/libdl.so.2 exists, but not libdl.so. To resolve the issue, I created a symlink to  /usr/lib64/libdl.so.2 as  /usr/lib64/libdl.so.

Is there a better way to solve this, maybe addig libdl.so.2 to the Posix NativeMethods module? 

Thanks!

**Comment by ied206** [comment]
Thanks for trying my library and testing it out. As a quick fix, I will separate Linux code and macOS. 

The issue turns out quite complicated due to the fragmentation of linux userspace library location and naming. Originally I have used `libdl.so.2`, but it was changed to `libdl` to support Linux and macOS with one code (macOS offers only `libdl.dylib`). 

## Solutions

### (Fastest) Separate Linux/macOS from shared POSIX code

Copy and paste `DllImport`ed libdl function definitions into two. One for Linux (`libdl.so.2`), and the other for macOS (`libdl.dylib`).

**Pros:** Fastest way to solve.
**Cons: ** We have to do similar things per target platform.

### Use .Net Core's NativeLibrary class

.Net Core 3.0 offers the new class, [NativeLibrary]([https://github.com/dotnet/corefx/issues/32015]), which solves this problem entirely. I have considered using it but was unable to. The API does not exist in .Net Standard, and shipping .Net Core assembly directly and keeping its forward-compatibility is hard.

[Zstandard.Net](https://github.com/bp74/Zstandard.Net/pull/7) have similar pull request. I will review their code.

**Pros:** Now the .Net Core runtime is responsible for exposing native library loading functionality. We can expect that Microsoft will take care of such fragmentation things.
**Cons:** Only available after .Net Core 3.0. .Net Core does not 100% guarantee the behavior compatibility of APIs over major update, unlike .Net Standard.

### Study how .Net Core runtime solved it

.Net Core team must have faced similar problems while implementing `DllImport` for Linux. I will review the code of CoreFX in the long run.

**Comment by ied206** [comment]
I patched the `libdl` DllImport code in commit b26e4caa0db65d1461da4fe1c28bc99a32cda61b.

If you would, please clone the develop branch and run the test (`dotnet test`) on CentOS.

**Comment by ied206** [comment]
The updated package was uploaded to [NuGet](https://www.nuget.org/packages/Joveler.DynLoader/1.2.1). It should work on CentOS, please try it.

**Comment by zcsizmadia** [comment]
Thanks for the update!

Compression.XZ is still referencing DynLoader 1.2.0, so I had to force to use the latest 1.2.1. After adding the PackageReference DybLoader 1.2.1 to the Compression.XZ.Test the test passed on CentOS 7.

**Comment by ied206** [comment]
Yes, I also am working on other libraries which depends on Joveler.DynLoader.

**Comment by ied206** [comment]
[Joveler.Compression.XZ](https://www.nuget.org/packages/Joveler.Compression.XZ/3.1.1) and its siblings were updated to reference `Joveler.DynLoader` 1.2,1. Please have a look.
